export const UI_STRINGS = {
  en: {
    greeting: "Hello",
    learningStatus: "You're learning",
    beginner: "Beginner Level",
    learning: "Learning:",
    switchLanguage: "Switch Language",
    todaysGoal: "Today's Goal",
    yourLessons: "Your Lessons",
    startPractice: "Start Practice",
    lessonCurrent: "CURRENT",
    locked: "LOCKED",
    minutes: "min",
    phrases: "phrases",
    home: "Home",
    progress: "Progress",
    profile: "Profile",
    lessonTitle: "Lesson 1: Basic Greetings",
    exit: "Exit",
    sayThisIn: "Say this in",  // "Say this in Kannada"
    expectedAnswer: "Expected answer:",
    showRomanization: "Show",
    hideRomanization: "Hide",
    romanization: "Romanization",
    clickAndSpeak: "Click microphone and speak",
    listening: "Listening...",
    analyzing: "Analyzing your pronunciation...",
    greatJob: "Great job!",
    youSaid: "You said:",
    pronunciationAnalysis: "Pronunciation Analysis:",
    hearOriginal: "Hear Original",
    tryAgain: "Try Again",
    nextPhrase: "Next Phrase",
    lessonComplete: "Lesson Complete! 🎉"
  },
  hi: {
    greeting: "नमस्ते",
    learningStatus: "आप सीख रहे हैं",
    beginner: "शुरुआती स्तर",
    learning: "सीख रहे हैं:",
    switchLanguage: "भाषा बदलें",
    todaysGoal: "आज का लक्ष्य",
    yourLessons: "आपके पाठ",
    startPractice: "अभ्यास शुरू करें",
    lessonCurrent: "वर्तमान",
    locked: "लॉक",
    minutes: "मिनट",
    phrases: "वाक्यांश",
    home: "होम",
    progress: "प्रगति",
    profile: "प्रोफ़ाइल",
    lessonTitle: "पाठ 1: बुनियादी अभिवादन",
    exit: "बाहर निकलें",
    sayThisIn: "इसे कहें",  // "इसे कन्नड़ में कहें"
    expectedAnswer: "अपेक्षित उत्तर:",
    showRomanization: "दिखाएं",
    hideRomanization: "छुपाएं",
    romanization: "रोमनीकरण",
    clickAndSpeak: "माइक्रोफोन पर क्लिक करें और बोलें",
    listening: "सुन रहा हूँ...",
    analyzing: "आपके उच्चारण का विश्लेषण कर रहे हैं...",
    greatJob: "बहुत बढ़िया!",
    youSaid: "आपने कहा:",
    pronunciationAnalysis: "उच्चारण विश्लेषण:",
    hearOriginal: "मूल सुनें",
    tryAgain: "फिर से कोशिश करें",
    nextPhrase: "अगला वाक्यांश",
    lessonComplete: "पाठ पूर्ण! 🎉"
  },
  ta: {
    greeting: "வணக்கம்",
    learningStatus: "நீங்கள் கற்கிறீர்கள்",
    beginner: "தொடக்க நிலை",
    learning: "கற்கிறீர்கள்:",
    switchLanguage: "மொழியை மாற்று",
    todaysGoal: "இன்றைய இலக்கு",
    yourLessons: "உங்கள் பாடங்கள்",
    startPractice: "பயிற்சியைத் தொடங்குங்கள்",
    lessonCurrent: "நடப்பு",
    locked: "பூட்டப்பட்டது",
    minutes: "நிமிடங்கள்",
    phrases: "சொற்றொடர்கள்",
    home: "முகப்பு",
    progress: "முன்னேற்றம்",
    profile: "சுயவிவரம்",
    lessonTitle: "பாடம் 1: அடிப்படை வாழ்த்துக்கள்",
    exit: "வெளியேறு",
    sayThisIn: "இதை சொல்லுங்கள்",
    expectedAnswer: "எதிர்பார்க்கப்படும் பதில்:",
    showRomanization: "காட்டு",
    hideRomanization: "மறை",
    romanization: "ரோமானியமாக்கம்",
    clickAndSpeak: "மைக்ரோஃபோனைக் கிளிக் செய்து பேசுங்கள்",
    listening: "கேட்கிறது...",
    analyzing: "உங்கள் உச்சரிப்பை பகுப்பாய்வு செய்கிறது...",
    greatJob: "அருமை!",
    youSaid: "நீங்கள் சொன்னது:",
    pronunciationAnalysis: "உச்சரிப்பு பகுப்பாய்வு:",
    hearOriginal: "அசலைக் கேளுங்கள்",
    tryAgain: "மீண்டும் முயற்சிக்கவும்",
    nextPhrase: "அடுத்த சொற்றொடர்",
    lessonComplete: "பாடம் முடிந்தது! 🎉"
  },
  te: {
    greeting: "నమస్కారం",
    learningStatus: "మీరు నేర్చుకుంటున్నారు",
    beginner: "ప్రారంభ స్థాయి",
    learning: "నేర్చుకుంటున్నారు:",
    switchLanguage: "భాషను మార్చండి",
    todaysGoal: "నేటి లక్ష్యం",
    yourLessons: "మీ పాఠాలు",
    startPractice: "అభ్యాసం ప్రారంభించండి",
    lessonCurrent: "ప్రస్తుతం",
    locked: "లాక్ చేయబడింది",
    minutes: "నిమిషాలు",
    phrases: "పదబంధాలు",
    home: "హోమ్",
    progress: "పురోగతి",
    profile: "ప్రొఫైల్",
    lessonTitle: "పాఠం 1: ప్రాథమిక శుభాకాంక్షలు",
    నిష్క్రమణ: "నిష్క్రమించు",
    sayThisIn: "దీన్ని ఇలా చెప్పు", // "దీన్ని కన్నడలో చెప్పు"
    expectedAnswer: "ఆశించిన సమాధానం:",
    showRomanization: "చూపించు",
    hideRomanization: "దాచు",
    romanization: "రోమనైజేషన్",
    clickAndSpeak: "మైక్రోఫోన్‌పై క్లిక్ చేసి మాట్లాడు",
    listening: "వినడం...",
    analysing: "మీ ఉచ్చారణను విశ్లేషించడం...",
    greatJob: "చాలా బాగుంది!",
    youSaid: "మీరు ఇలా అన్నారు:",
    pronunciationAnalysis: "ఉచ్చారణ విశ్లేషణ:",
    hearOriginal: "అసలు వినండి",
    tryAgain: "మళ్ళీ ప్రయత్నించండి",
    nextFrase: "తదుపరి పదబంధం",
    lessonComplete: "పాఠం పూర్తయింది! 🎉"
  },
  kn: {
    greeting: "ನಮಸ್ಕಾರ",
    learningStatus: "ನೀವು ಕಲಿಯುತ್ತಿದ್ದೀರಿ",
    beginner: "ಪ್ರಾರಂಭಿಕ ಹಂತ",
    learning: "ಕಲಿಯುತ್ತಿದ್ದೀರಿ:",
    switchLanguage: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
    todaysGoal: "ಇಂದಿನ ಗುರಿ",
    yourLessons: "ನಿಮ್ಮ ಪಾಠಗಳು",
    startPractice: "ಅಭ್ಯಾಸ ಪ್ರಾರಂಭಿಸಿ",
    lessonCurrent: "ಪ್ರಸ್ತುತ",
    locked: "ಲಾಕ್ ಮಾಡಲಾಗಿದೆ",
    minutes: "ನಿಮಿಷಗಳು",
    phrases: "ನುಡಿಗಟ್ಟುಗಳು",
    home: "ಮುಖಪುಟ",
    progress: "ಪ್ರಗತಿ",
    profile: "ಪ್ರೊಫೈಲ್",
    lessonTitle: "ಪಾಠ 1: ಮೂಲ ಶುಭಾಶಯಗಳು",
    ನಿರ್ಗಮನ: "ನಿರ್ಗಮಿಸು",
    sayThisIn: "ಇದನ್ನು ಇಲ್ಲಿ ಹೇಳಿ", // "ಇದನ್ನು ಕನ್ನಡದಲ್ಲಿ ಹೇಳಿ"
    expectedAnswer: "ನಿರೀಕ್ಷಿತ ಉತ್ತರ:",
    showRomanization: "ತೋರಿಸು",
    hideRomanization: "ಮರೆಮಾಡಿ",
    romanization: "ರೋಮನೀಕರಣ",
    clickAndSpeak: "ಮೈಕ್ರೊಫೋನ್ ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ಮಾತನಾಡಿ",
    listening: "Listening...",
    analysing: "Analysing your explanation...",
    greatJob: "Great job!",
    youSaid: "You said:",
    pronunciationAnalysis: "Pronucation Analysis:",
    hearOriginal: "Hear Original",
    tryAgain: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    nextPhrase: "ಮುಂದಿನ ನುಡಿಗಟ್ಟು",
    lessonComplete: "ಪಾಠ ಪೂರ್ಣಗೊಂಡಿದೆ! 🎉"
  },
  mr: {
    greeting: "नमस्कार",
    learningStatus: "तुम्ही शिकत आहात",
    beginner: "सुरुवातीची पातळी",
    learning: "शिकत आहात:",
    switchLanguage: "भाषा बदला",
    todaysGoal: "आजचे ध्येय",
    yourLessons: "तुमचे धडे",
    startPractice: "सराव सुरू करा",
    lessonCurrent: "वर्तमान",
    locked: "लॉक केलेले",
    minutes: "मिनिटे",
    phrases: "वाक्यांश",
    home: "होम",
    progress: "प्रगती",
    profile: "प्रोफाइल",
    lessonTitle: "धडा १: मूलभूत शुभेच्छा",
    exit: "बाहेर पडा",
    sayThisIn: "हे आत सांगा", // "हे कन्नडमध्ये सांगा"
    expectedAnswer: "अपेक्षित उत्तर:",
    showRomanization: "दाखवा",
    hideRomanization: "Hide",
    romanization: "रोमनाइजेशन",
    clickAndSpeak: "मायक्रोफोनवर क्लिक करा आणि बोला",
    listening: "ऐकत आहे...",
    analysing: "तुमच्या उच्चाराचे विश्लेषण करत आहे...",
    greatJob: "छान काम!",
    youSaid: "तुम्ही म्हणालात:",
    pronounceAnalysis: "उच्चार विश्लेषण:",
    hearOriginal: "मूळ ऐका",
    tryAgain: "पुन्हा प्रयत्न करा",
    nextPhrase: "पुढील वाक्यांश",
    lessonComplete: "धडा पूर्ण झाला! 🎉"
  }
};


export const getUIStrings = (languageCode) => {
  return UI_STRINGS[languageCode] || UI_STRINGS.en;
};